- .vuepress/config.js
Thanks @ravenac95 for fixing this subtle bug.
> Make GitHub Pages less unhappy

- README.md
Seems like we should add the client here?
> Add oasis.js to change summary

- src/.vuepress/config.js
- src/tutorials/ballot.md
- Makes `Tutorials` tab in navbar collapsable
- Fixes code indentation issues in voting tutorial docs + add a couple of comments
> Tutorials Documentation Nits

- src/.vuepress/config.js
This will resolve #78, hopefully
> Integrate intercom with Oasis documentation

- src/tutorials/ballot.md
Update ballot tutorial docs to specify how to connect via developer gateway.
> Ballot with Developer Gateway

- src/.vuepress/config.js
Add link to https://docs.rs/oasis-std.
> Link to Rust docs

- src/tutorials/ballot.md
... by setting API token to gateway directly and not through headers.
> Harmonizing setting api token with tutorial code

- src/operators/architectural-overview.md
- src/operators/current-testnet-parameters.md
- src/operators/hardware-recommendations.md
- src/operators/joining-the-testnet.md
- src/operators/maintenance/wiping-node-state.md
- src/operators/overview.md
- src/operators/prerequisites.md
We are preparing to have these docs merged in for tomorrow. The docs have been reviewed by @david-yan and myself. 
Feel free to suggest any more adjustments
> Merge latest docs from private operator docs

- src/operators/joining-the-testnet.md
Fixes to problems we found while going through deployment.
> Changes to joining-the-testnet.md

- src/operators/joining-the-testnet.md
- src/operators/prerequisites.md
Fixed broken link in description of entity and provided clarity about current working branch when building oasis-node binaries from scratch. Also added clarification about server IP.
> Fixed broken link and provided clarity about current working branch.

- src/.vuepress/config.js
- src/operators/stake-management.md
Docs part of PR for https://github.com/oasislabs/oasis-core/issues/2275
This PR adds
* *Stake management in details using CLI* chapter for the node operators.
Merge after https://github.com/oasislabs/oasis-core/pull/2293 is merged.
> operators: stake management chapter

- src/.vuepress/config.js
- src/operators/joining-the-testnet.md
- src/operators/sentry-node.md
- bunch of TODOs
- references to existing descriptions of sentry node setup
> sentry node docs

- src/operators/current-testnet-parameters.md
- src/operators/prerequisites.md
General improvements to style and formatting.
> Improve Operator Docs: Prerequisites and Current Testnet Parameters

- src/operators/joining-the-testnet.md
- src/operators/sentry-node.md
Addresses some fixes from community feedback.
> Various Fixes via Feedback

- src/operators/stake-management.md
Update to use the unified `oasis-node consensus submit_tx` interface
> Update transaction submit commands

- src/.vuepress/config.js
> config: add Handling Network Upgrades link

- src/operators/creating-an-entity-package.md
- src/operators/staking-competition-rules.md
> Entity Package Creation

- src/.vuepress/config.js
- src/operators/TheQuest_rules
- src/operators/the-quest-rules.md
> Update and rename staking-competition-rules.md to TheQuest_rules

- src/operators/sentry-node.md
Missed this one in https://github.com/oasislabs/docs/pull/165
> Update DB backend to badger in sentry node config

- src/operators/joining-the-testnet.md
Also fixed a slight spelling mistake
> Updated the `Checking that Your Node is Properly Registered` Guide Section

- src/operators/joining-the-testnet.md
> fix date typo

- src/operators/maintenance/wiping-node-state.md
> wiping-node-state: use the 'oasis-node unsafe-reset' command

- src/operators/current-testnet-parameters.md
- src/operators/maintenance/handling-network-upgrades.md
Update changelog and upgrade instructions.
> Questnet upgrade updates

- src/.vuepress/config.js
- src/hsm/ledger.md
Resolves https://github.com/oasislabs/docs/issues/185
> Add section for Ledger support

- src/operators/sentry-node.md
updates sentry node docs to work with latest release
> update sentry-node docs

- src/operators/current-testnet-parameters.md
> Consolidate upgrade steps

- src/hsm/ledger.md
New commands for https://github.com/oasislabs/oasis-core/pull/2610
> Update Ledger docs for new extract command

- src/operators/joining-the-testnet.md
TODO:
- Will do that as a separate PR
Implements the first part of #197.
> operators: Update Joining the Testnet doc for Oasis Core 20.3

- src/operators/architectural-overview.md
Updated architecture page to include information on parallel runtimes and
> Updated architecture page

- src/.vuepress/config.js
- src/operators/architecture-overview.md
Removed content from architecture overview that we're not doing anymore.
Also updated title
> Removed content from architecture overview

- src/operators/the-quest-rules.md
Here's our new The Quest challenges, transferred from our internal shared doc.
> operators: Next phase of The Quest challenges

- src/.vuepress/config.js
- src/operators/maintenance/checking-account-nonce.md
We forgot about this one when closing https://github.com/oasislabs/docs/issues/197.
> operators: Update Checking Your Account's nonce doc

- src/operators/current-testnet-parameters.md
> Add instructions for 2020-03-05 upgrade

- src/operators/stake-management.md
Here's an example of an amend commission schedule transaction.
> operators: Add docs for amend commission schedule

- src/operators/joining-the-testnet.md
The minimum amount needed to register a node is actually 200 tokens--100 for entity registration plus 100 for node registration.
> Update testnet staking thresholds

- src/operators/current-testnet-parameters.md
- src/operators/maintenance/handling-network-upgrades.md
Replace state patching instructions with instructions on how to verify the provided genesis document.
Streamline and cross-reference Deployment Change Log and Handling Network Upgrades guide.
> operators: Overhaul network upgrade docs

- src/operators/the-quest-rules.md
Here's the new availability rewards
> operators: new availability rewards

- src/operators/stake-management.md
> operators: Update Stake Management docs for Oasis Core 20.4

- src/operators/stake-management.md
> operators: Show how tx fees work in Stake Management docs

- src/operators/current-testnet-parameters.md
Feel free to merge this once approved.
> operators: update oasis-node version to 20.4.1

- src/.vuepress/config.js
- src/operators/joining-the-testnet.md
Flag defaults to `false`: https://github.com/oasislabs/oasis-core/blob/c8e43814070f4d39ac0ff11f28886d313d850316/go/consensus/tendermint/tendermint.go#L1366
> operators: unneeded 'addr_book_lenient: false' flag

- src/operators/the-quest-rules.md
> quest: new availability scoring

- src/operators/stake-management.md
Follow-up from #207, needs to be vetted by legal.
> operators: Reference consensus parameter update support in Staking docs

- src/operators/the-quest-rules.md
Updated based on previous winners and upcoming May competition
> Updates to questnet rules

- src/operators/incentives-proposal.md
Add more info about consensus voting power.
> More on consensus voting power

- src/.vuepress/config.js
- src/hsm/ledger.md
- src/operators/architecture-overview.md
- src/operators/creating-an-entity-package.md
- src/operators/current-testnet-parameters.md
- src/operators/incentives-proposal.md
- src/operators/migrating-questnet-entities.md
- src/operators/overview.md
- src/operators/running-node-on-amber-network.md
- src/operators/sentry-node.md
- src/operators/stake-management.md
Adds:
* Migrating entity docs
Updates:
* Updates "Joining the Testnet" to be "Running a Node on Amber Network"
* Updates a variety of links
> Amber Network Entity Submission

- src/operators/current-testnet-parameters.md
Placeholder until we have a genesis doc.
> Update current-testnet-parameters.md for Amber network

- src/operators/current-testnet-parameters.md
> Updated seed node

- src/operators/sentry-node.md
Fix: #263 
Requires: https://github.com/oasisprotocol/oasis-core/issues/3015 (or a workaround for manually parsing out the pubkey from the certificate file)
> fix sentry-node configuration setup

- .github/workflows/ci.yml
- README.md
See commit messages for more detailed info.
> Various improvements to Operator docs

- src/operators/current-testnet-parameters.md
Just a more precise improvement to the docs.
> Use CVE ID for CVE-2020-15091

- src/operators/current-testnet-parameters.md
* Add proper seed address
* Update changelog
> 2020-08-06: Upgrade Releases
